name: Lint

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        toolchain: [nightly]
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy
          profile: minimal
          override: true

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1.5.2
        if: runner.os != 'macOS'
        with:
          version: "12.0"
          directory: ${{ runner.temp }}/llvm

      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
        if: runner.os == 'linux'

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-clippy-rustc-${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        if: runner.os == 'linux'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --workspace --tests

      - name: Run cargo fmt
        if: runner.os == 'linux'
        run: cargo fmt --all -- --check

      - name: Run cargo test
        run: cargo test
