name: Lint

on: [push, pull_request]

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly 
          components: clippy
          profile: minimal
          override: true

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1.3.0
        with:
          version: "12.0"
          directory: ${{ runner.temp }}/llvm

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-clippy-rustc-${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --workspace --tests

  rustfmt:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
          profile: minimal
          override: true

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1.3.0
        with:
          version: "12.0"
          directory: ${{ runner.temp }}/llvm

      - name: Run cargo fmt
        run: cargo fmt --all -- --check